### ISSUE TITLE
Add Simplex Search

### ISSUE THREAD

**Issue by sudz123** [sudz123/Optimizer#101]
K. Deb Pg. 95 ; Make necessary changes in `Optimizer.h`

**Comment by Madoxen** [comment]
I will do it.

**Comment by sudz123** [comment]
Great! @Madoxen take a look at the other multivariable algorithms for how the code structure should be. And although a few things might seem easy but here is the deal. Every time you call `obj_func` you are increasing processing time. So for eg. you can check how `Fibonnaci search` has been implemented to make sure I am only calling the objective function when necessary and there are no redundant calls. So make sure you keep this in mind. 

This is because although currently we are making the algorithm just return the optimum point, we plan to change the return type of all the functions to an instance of the class in `util.h`which also contains the number of function evaluations. In K. Deb too this is given a lot of importance and the aim of most algorithms is to reduce this number to as low as possible. Do let me know if you have any doubts.

**Comment by Madoxen** [comment]
Hey, I just wanted if you completed tests for Simplex. Also when you have been merging it 2 days ago you had a question about why delta = 0,25 when n==3. I've taken the values from appendix 3 in Simplex Search function, but I don't really know why it should be like that
