### ISSUE TITLE
Need to add macros

### ISSUE THREAD

**Issue by sudz123** [sudz123/Optimizer#110]
In `util.h` we have included `fstream` and `vector` without std predefined macros. We need to add them.

**Comment by Pokinawa** [comment]
I am not quite sure I understand what you're asking for here. Both fstream and vector have a standard header guard in them, something like -
```
#ifndef _FSTREAM_H
#define _FSTREAM_H
```
Thus, the header code won't be included twice. Could you elaborate what you're trying to achieve by putting another guard in util.h?

**Comment by sudz123** [comment]
Oh, you learn something new everyday. I did not know this, thanks!
