### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by sudz123** [sudz123/Optimizer#37]
Add a link to the hacktoberfest teaser video.

**Comment by tulikavijay** [comment]
hey! can i take this up?

**Comment by sudz123** [comment]
Sure!

**Comment by tulikavijay** [comment]
Where exactly do you want me to add it?

**Comment by sudz123** [comment]
You can add a line below the submit 5 PRs para

**Comment by Anne97** [comment]
Hello, can I take this up?

**Comment by sudz123** [comment]
Sure
