### ISSUE TITLE
Add basic printing function in util.h

### ISSUE THREAD

**Issue by sudz123** [sudz123/Optimizer#76]
`util.h` has two unimplemented functions in the class `Optimum`
- SaveAsTxt()
- SaveAsCsv()

On being called these should respectively create a txt/csv file. These files should have each line storing data from one row of `Eigen::MatrixXd path`. Should be fairly easy.

**Comment by Madoxen** [comment]
Hey, can i try to implement those functions?

**Comment by sudz123** [comment]
Sure have a go, comment if any issues come up, best of luck :)

**Comment by Madoxen** [comment]
Hey, just one question, should data files be saved in some specific location and specific naming? Or the file should be appended when the new data will be written?

**Comment by sudz123** [comment]
Currently maybe inside a folder called *results* in the folder where the cpp function is present. The name of the file is not important for now. Currently no need to append the data, create a new file everytime the function is called which overwrites the previous file. I'll think of a naming convention soon.

**Comment by Madoxen** [comment]
One more question, probably the last. How can I test those two functions?

**Comment by Madoxen** [comment]
I've managed to test these two methods and sent a pull request.

**Comment by sudz123** [comment]
Great work!
